version = 0.1
[default.deploy.parameters]
stack_name = "agora-foi-13"
resolve_s3 = true
s3_prefix = "agora-foi-13"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true
